import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
const errors = [];
page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
page.on('pageerror', err => errors.push(err.message));
await page.goto('https://gian-lucca-ranch-8v0d4x968-simplebalance89-ais-projects.vercel.app/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
console.log('Console errors:', errors.length);
errors.forEach(e => console.log(' -', e));
await browser.close();
